apiVersion: v1
kind: Service
metadata:
  name: workshop-slides
  namespace: workshop-slides
  labels:
    app: workshop-slides
spec:
  selector:
    app: workshop-slides
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
