apiVersion: v1
kind: Service
metadata:
  name: workload-simulator
  namespace: vpa-demo
spec:
  selector:
    app: workload-simulator
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
